language: c

compiler:
  - gcc

sudo: required

dist: trusty

env:
  global:
    - PREFIX="$HOME/build"
    - PATH="$PREFIX/bin:$PATH"
    - CFLAGS="-L$PREFIX/lib"
    - CPPFLAGS="-I$PREFIX/include"
    - PKG_CONFIG_PATH="$PREFIX/lib/pkgconfig"
    - CC="gcc-4.9"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - "ppa:jbboehr/check"
    packages:
      - automake
      - bison
      - check
      - flex
      - gcc-4.9
      - lcov
      - libjson-c-dev
      - libpcre3-dev
      - libtalloc-dev
      - libyaml-dev
      - pkg-config

cache: false

branches:
  only:
    - master
    - travis

before_install:
  - travis_retry gem install coveralls-lcov

install:
  - ./.travis.sh
  - ./bootstrap
  - ./configure --prefix="$PREFIX"  CFLAGS="--coverage -fprofile-arcs -ftest-coverage $CFLAGS" LDFLAGS="--coverage"
  - make clean all

before_script:
  - lcov --directory . --zerocounters
  - lcov --directory . --capture --compat-libtool --initial --output-file coverage.info

script:
  - make check install

after_success:
  - lcov --no-checksum --directory . --capture --compat-libtool --output-file coverage.info
  - lcov --remove coverage.info "/usr*" --remove coverage.info "*/tests/*" --compat-libtool --output-file coverage.info
  - coveralls-lcov coverage.info

after_failure:
  - for i in `find tests -name "*.log" 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

