language: c

sudo: required

dist: xenial

env:
  global:
    - ARCH="amd64"
    - COVERAGE="true"
  matrix:
    - MYCC="gcc-4.9"
    - MYCC="gcc-5"
    - MYCC="gcc-6"
    - MYCC="gcc-7"
# https://github.com/linux-test-project/lcov/issues/58
    - MYCC="gcc-8"
      COVERAGE="false"
    - MYCC="gcc-9"
      COVERAGE="false"
    - MYCC="gcc-5"
      ARCH="i386"
      COVERAGE="false"
    - MYCC="clang-3.8"
      COVERAGE="false"
    - MYCC="gcc-9"
      COVERAGE="false"
      HARDENING="true"

matrix:
  include:
    - language: nix
      before_install:
      install:
      before_script:
      script: nix-build --argstr handlebarscVersion $TRAVIS_BRANCH
      after_success:
      after_failure:
      env:
        - MYCC=

cache: false

branches:
  only:
    - master
    - travis
    - dev-1.x

before_install:
    - source ./.travis.sh
    - travis_retry install_apt_packages
    - travis_retry install_json_c
    - travis_retry install_coveralls_lcov

install: install
before_script: before_script
script: script
after_success: after_success
after_failure: after_failure
