language: c

dist: focal

matrix:
    fast_finish: true
    allow_failures:
    - env:
      - MYCC="gcc-9"
      - ARCH="armhf"
    # - env:
    #   - MYCC="gcc-9"
    #   - VALGRIND=true
    include:
# gcc-5, xenial
    - dist: xenial
      env:
      - MYCC="gcc-5"
      - GCOV="gcov-5"
# gcc-6, bionic
    - dist: bionic
      env:
      - MYCC="gcc-6"
      - GCOV="gcov-6"
# gcc-7, bionic
    - dist: bionic
      env:
      - MYCC="gcc-7"
      - GCOV="gcov-7"
# gcc-8, focal
    - dist: focal
      env:
      - MYCC="gcc-8"
      - GCOV="gcov-8"
# gcc-9, focal
    - dist: focal
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
# gcc-9, focal, arm64
    - dist: focal
      arch: arm64
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
# gcc-9, focal, armhf
    - dist: focal
      arch: arm64
      env:
      - MYCC="gcc-9"
      - ARCH="armhf"
# gcc-9, focal, i386
    - dist: focal
      env:
      - MYCC="gcc-9"
      - ARCH="i386"
# gcc-9, focal, ppc64le
    - dist: focal
      arch: ppc64le
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
# gcc-9, focal, s390x
    - dist: focal
      arch: s390x
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
# gcc-9, focal, debug
    - dist: focal
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
      - DEBUG=true
# gcc-9, focal, lto
    - dist: focal
      env:
      - MYCC="gcc-9"
      - LTO=true
# gcc-9, focal, no hardening
    - dist: focal
      env:
      - MYCC="gcc-9"
      - HARDENING=false
# gcc-9, focal, minimal
    - dist: focal
      env:
      - MYCC="gcc-9"
      - GCOV="gcov-9"
      - MINIMAL=true
# gcc-9, focal, valgrind
    # - dist: focal
    #   env:
    #   - MYCC="gcc-9"
    #   - VALGRIND=true
# gcc-10, focal, toolchain test
    - dist: focal
      env: MYCC="gcc-10"
# clang-3.8, xenial
    - dist: xenial
      env: MYCC="clang-3.8"
# clang-6.0, bionic
    - dist: bionic
      env: MYCC="clang-6.0"
# clang-10, focal
    - dist: focal
      env: MYCC="clang-10"

branches:
  only:
    - master
    - travis
    - dev-1.x
    - ci

before_install:
    - source ./.ci/travis.sh
    - travis_retry before_install

install: install
script: script
after_success: after_success
after_failure: after_failure
