language: c

sudo: required

dist: xenial

env:
  matrix:
    - MYCC="gcc-4.9"
      COVERAGE="true"
    - MYCC="gcc-5"
      COVERAGE="true"
    - MYCC="gcc-6"
      COVERAGE="true"
    - MYCC="gcc-7"
      COVERAGE="true"
    - MYCC="gcc-8"
    - MYCC="gcc-9"
# 32bit
    - MYCC="gcc-5"
      ARCH="i386"
# clang
    - MYCC="clang-3.8"
# no hardening
    - MYCC="gcc-9"
      HARDENING="false"
# lto
    - MYCC="gcc-9"
      LTO="true"
# minimal
    - MYCC="gcc-9"
      MINIMAL="true"
# valgrind
# not sure why but this isn't working, running it on HerculesCI instead
#    - MYCC="gcc-9"
#      VALGRIND="true"

matrix:
  include:
    - language: nix
      before_install:
      install:
      before_script: export NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-${NIX_CHANNEL}.tar.gz
      script: nix-build --argstr handlebarscVersion $TRAVIS_BRANCH
      after_success:
      after_failure:
      env:
        - MYCC=
        - NIX_CHANNEL=20.03

cache: false

branches:
  only:
    - master
    - travis
    - dev-1.x

before_install:
    - source ./.travis.sh
    - travis_retry install_apt_packages
    - travis_retry install_coveralls_lcov

install:
    - configure_handlebars
    - make_handlebars
    - install_handlebars

before_script: initialize_coverage

script:
    - test_handlebars
    - run_handlebars_benchmark

after_success: upload_coverage
after_failure: dump_logs
