language: c

compiler:
  - gcc

branches:
  only:
    - master
    - travis-fix

sudo: false

# autoconf automake gawk gcc git-core libtool m4 make
addons:
  apt:
    packages:
      - bison
      - flex
      - lcov
      - libjson0-dev
      - libpcre3-dev
      - libtalloc-dev
      - pkg-config

cache:
  directories:
    - $HOME/build

install:
  - ./.travis.sh
  
script:
  - export PATH="$HOME/build/bin:$PATH"
  - export CFLAGS="-L$HOME/build/lib"
  - export CPPFLAGS="-I$HOME/build/include"
  - export PKG_CONFIG_PATH="$HOME/build/lib/pkgconfig"
  - ./bootstrap
  - ./configure --prefix=$HOME/build
  - make all check install
